apiVersion: v1
kind: Service
metadata:
  name: x1frontend-k8s
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP 
      port: 8080
      targetPort: 5000
  selector:
    app: x1frontend-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x1frontend-k8s
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: x1frontend-k8s
  template:
    metadata:
      labels:
        app: x1frontend-k8s
    spec:
      containers:
        - name: x1frontend-k8s
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5000
              protocol: TCP